### PR TITLE
updated jackson-databind to a version 2.9.5 and uplifted parent version.

### LINKED ISSUE #7: Security vulnerability in Jackson-databind
### Description
Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.5 or later

### Motivation
GitHub found a potential security vulnerability 
in com.fasterxml.jackson.core:jackson-databind

### Exemplification
security issues / breach

### Benefits
Close down potental security problem

### Possible Drawbacks
Non forseen

### PR DESCRIPTION
**Pull request by ZVADHEM**
resolved #7 [https://github.com/eiffel-community/eiffel-remrem-parent/issues/7]

### CODE REVIEW

**Comment by xvinosi-github** [comment]
+1

**Review by xdurvak — COMMENTED** [review]
please add changes in changelog.md file

**Review by xdurvak — COMMENTED** [review]
+1

**Comment by xvinosi-github** [comment]
+1

**Pull request merged**
